language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - python setup.py develop
  - pip install pytest-cov coveralls
script:
  - py.test --cov collection_filter
after_success:
  - coveralls
